version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8100:8080"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"